version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.7.4
    commands:
      - echo "installing Bundler..."
      - echo gem install bundler
      - bundle install
    pre_build:
      commands:
        - echo "preparing database to run tests..."
        - bundle exec rails db:create RAILS_ENV=test
        - bundle exec rails db:migrate RAILS_ENV=test
    build:
      commands:
        -echo "running tests..."
        -bundle exec rspec spec
